typography_spectrum: 0.3107698322273791
color:
  brandStrength: 0.13727153651416302
  lightness: 0.028743345057591796
  saturation: 0.08113969815894961
  rhythmicContrast: 0.7995035625062883
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
layout_spectrum: 0.45614102529361844
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/41fcb587-466d-4ef7-99b7-9db3d4d8ee9f.png
name: Trondheimkajakk.no
navigation:
  - name: Instagram stream
    url: 'https://www.instagram.com/trondheimkajakk/'
    type: external
  - name: Turer
    id: aaf20032-029c-4882-9eb6-55890620f4ff
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4c03ed6-b009-4e62-9c9e-1d70b9faff30.png
title: Trondheimkajakk
description: En unik opplevelse
